version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ericisw8n/pythontest:1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
